// <auto-generated />
namespace Hadco.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initialCoreTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialCoreTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201510211714454_initialCoreTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
