namespace Hadco.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedTrackedEntities : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Employees", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.Employees", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.Employees", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.Employees", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.DailyApprovals", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.DailyApprovals", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.DailyApprovals", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.DailyApprovals", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.DowntimeTimers", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.DowntimeTimers", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.DowntimeTimers", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.DowntimeTimers", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.LoadTimers", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.LoadTimers", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.LoadTimers", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.LoadTimers", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.LoadTimerEntries", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.LoadTimerEntries", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.LoadTimerEntries", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.LoadTimerEntries", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.Timesheets", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.Timesheets", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.Timesheets", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.Timesheets", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.EmployeeTimers", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EmployeeTimers", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EmployeeTimers", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.EmployeeTimers", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.EmployeeJobTimers", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EmployeeJobTimers", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EmployeeJobTimers", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.EmployeeJobTimers", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.EmployeeJobEquipmentTimers", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EmployeeJobEquipmentTimers", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EmployeeJobEquipmentTimers", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.EmployeeJobEquipmentTimers", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.JobTimers", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.JobTimers", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.JobTimers", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.JobTimers", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.EmployeeTimecards", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EmployeeTimecards", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EmployeeTimecards", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.EmployeeTimecards", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.EmployeeTimerEntries", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EmployeeTimerEntries", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EmployeeTimerEntries", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.EmployeeTimerEntries", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.EquipmentTimers", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EquipmentTimers", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EquipmentTimers", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.EquipmentTimers", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.EquipmentTimerEntries", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EquipmentTimerEntries", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.EquipmentTimerEntries", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.EquipmentTimerEntries", "ModifiedEmployeeID", c => c.Int());
            AddColumn("dbo.RoleAuthActivities", "CreatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.RoleAuthActivities", "UpdatedOn", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.RoleAuthActivities", "CreatedEmployeeID", c => c.Int());
            AddColumn("dbo.RoleAuthActivities", "ModifiedEmployeeID", c => c.Int());
            CreateIndex("dbo.Employees", "CreatedEmployeeID");
            CreateIndex("dbo.DailyApprovals", "CreatedEmployeeID");
            CreateIndex("dbo.DowntimeTimers", "CreatedEmployeeID");
            CreateIndex("dbo.LoadTimers", "CreatedEmployeeID");
            CreateIndex("dbo.LoadTimerEntries", "CreatedEmployeeID");
            CreateIndex("dbo.Timesheets", "CreatedEmployeeID");
            CreateIndex("dbo.EmployeeTimers", "CreatedEmployeeID");
            CreateIndex("dbo.EmployeeJobTimers", "CreatedEmployeeID");
            CreateIndex("dbo.EmployeeJobEquipmentTimers", "CreatedEmployeeID");
            CreateIndex("dbo.JobTimers", "CreatedEmployeeID");
            CreateIndex("dbo.EmployeeTimecards", "CreatedEmployeeID");
            CreateIndex("dbo.EmployeeTimerEntries", "CreatedEmployeeID");
            CreateIndex("dbo.EquipmentTimers", "CreatedEmployeeID");
            CreateIndex("dbo.EquipmentTimerEntries", "CreatedEmployeeID");
            CreateIndex("dbo.RoleAuthActivities", "CreatedEmployeeID");
            AddForeignKey("dbo.Employees", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.DailyApprovals", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.DowntimeTimers", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.LoadTimers", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.LoadTimerEntries", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.Timesheets", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.EmployeeTimers", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.EmployeeJobTimers", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.EmployeeJobEquipmentTimers", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.JobTimers", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.EmployeeTimecards", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.EmployeeTimerEntries", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.EquipmentTimers", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.EquipmentTimerEntries", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
            AddForeignKey("dbo.RoleAuthActivities", "CreatedEmployeeID", "dbo.Employees", "EmployeeID");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.RoleAuthActivities", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.EquipmentTimerEntries", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.EquipmentTimers", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.EmployeeTimerEntries", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.EmployeeTimecards", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.JobTimers", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.EmployeeJobEquipmentTimers", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.EmployeeJobTimers", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.EmployeeTimers", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.Timesheets", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.LoadTimerEntries", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.LoadTimers", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.DowntimeTimers", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.DailyApprovals", "CreatedEmployeeID", "dbo.Employees");
            DropForeignKey("dbo.Employees", "CreatedEmployeeID", "dbo.Employees");
            DropIndex("dbo.RoleAuthActivities", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.EquipmentTimerEntries", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.EquipmentTimers", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.EmployeeTimerEntries", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.EmployeeTimecards", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.JobTimers", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.EmployeeJobEquipmentTimers", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.EmployeeJobTimers", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.EmployeeTimers", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.Timesheets", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.LoadTimerEntries", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.LoadTimers", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.DowntimeTimers", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.DailyApprovals", new[] { "CreatedEmployeeID" });
            DropIndex("dbo.Employees", new[] { "CreatedEmployeeID" });
            DropColumn("dbo.RoleAuthActivities", "ModifiedEmployeeID");
            DropColumn("dbo.RoleAuthActivities", "CreatedEmployeeID");
            DropColumn("dbo.RoleAuthActivities", "UpdatedOn");
            DropColumn("dbo.RoleAuthActivities", "CreatedOn");
            DropColumn("dbo.EquipmentTimerEntries", "ModifiedEmployeeID");
            DropColumn("dbo.EquipmentTimerEntries", "CreatedEmployeeID");
            DropColumn("dbo.EquipmentTimerEntries", "UpdatedOn");
            DropColumn("dbo.EquipmentTimerEntries", "CreatedOn");
            DropColumn("dbo.EquipmentTimers", "ModifiedEmployeeID");
            DropColumn("dbo.EquipmentTimers", "CreatedEmployeeID");
            DropColumn("dbo.EquipmentTimers", "UpdatedOn");
            DropColumn("dbo.EquipmentTimers", "CreatedOn");
            DropColumn("dbo.EmployeeTimerEntries", "ModifiedEmployeeID");
            DropColumn("dbo.EmployeeTimerEntries", "CreatedEmployeeID");
            DropColumn("dbo.EmployeeTimerEntries", "UpdatedOn");
            DropColumn("dbo.EmployeeTimerEntries", "CreatedOn");
            DropColumn("dbo.EmployeeTimecards", "ModifiedEmployeeID");
            DropColumn("dbo.EmployeeTimecards", "CreatedEmployeeID");
            DropColumn("dbo.EmployeeTimecards", "UpdatedOn");
            DropColumn("dbo.EmployeeTimecards", "CreatedOn");
            DropColumn("dbo.JobTimers", "ModifiedEmployeeID");
            DropColumn("dbo.JobTimers", "CreatedEmployeeID");
            DropColumn("dbo.JobTimers", "UpdatedOn");
            DropColumn("dbo.JobTimers", "CreatedOn");
            DropColumn("dbo.EmployeeJobEquipmentTimers", "ModifiedEmployeeID");
            DropColumn("dbo.EmployeeJobEquipmentTimers", "CreatedEmployeeID");
            DropColumn("dbo.EmployeeJobEquipmentTimers", "UpdatedOn");
            DropColumn("dbo.EmployeeJobEquipmentTimers", "CreatedOn");
            DropColumn("dbo.EmployeeJobTimers", "ModifiedEmployeeID");
            DropColumn("dbo.EmployeeJobTimers", "CreatedEmployeeID");
            DropColumn("dbo.EmployeeJobTimers", "UpdatedOn");
            DropColumn("dbo.EmployeeJobTimers", "CreatedOn");
            DropColumn("dbo.EmployeeTimers", "ModifiedEmployeeID");
            DropColumn("dbo.EmployeeTimers", "CreatedEmployeeID");
            DropColumn("dbo.EmployeeTimers", "UpdatedOn");
            DropColumn("dbo.EmployeeTimers", "CreatedOn");
            DropColumn("dbo.Timesheets", "ModifiedEmployeeID");
            DropColumn("dbo.Timesheets", "CreatedEmployeeID");
            DropColumn("dbo.Timesheets", "UpdatedOn");
            DropColumn("dbo.Timesheets", "CreatedOn");
            DropColumn("dbo.LoadTimerEntries", "ModifiedEmployeeID");
            DropColumn("dbo.LoadTimerEntries", "CreatedEmployeeID");
            DropColumn("dbo.LoadTimerEntries", "UpdatedOn");
            DropColumn("dbo.LoadTimerEntries", "CreatedOn");
            DropColumn("dbo.LoadTimers", "ModifiedEmployeeID");
            DropColumn("dbo.LoadTimers", "CreatedEmployeeID");
            DropColumn("dbo.LoadTimers", "UpdatedOn");
            DropColumn("dbo.LoadTimers", "CreatedOn");
            DropColumn("dbo.DowntimeTimers", "ModifiedEmployeeID");
            DropColumn("dbo.DowntimeTimers", "CreatedEmployeeID");
            DropColumn("dbo.DowntimeTimers", "UpdatedOn");
            DropColumn("dbo.DowntimeTimers", "CreatedOn");
            DropColumn("dbo.DailyApprovals", "ModifiedEmployeeID");
            DropColumn("dbo.DailyApprovals", "CreatedEmployeeID");
            DropColumn("dbo.DailyApprovals", "UpdatedOn");
            DropColumn("dbo.DailyApprovals", "CreatedOn");
            DropColumn("dbo.Employees", "ModifiedEmployeeID");
            DropColumn("dbo.Employees", "CreatedEmployeeID");
            DropColumn("dbo.Employees", "UpdatedOn");
            DropColumn("dbo.Employees", "CreatedOn");
        }
    }
}
